version: '3'
services:
  application:
    build: .
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - main_network
    depends_on:
      - queue

  loadbalancer:
    build: ./loadbalancer
    ports:
      - 80:80
    networks:
      - main_network
    depends_on:
      - application

  queue:
    image: redis
    networks:
      - main_network
    ports:
      - 6379:6379

networks:
  main_network:
