version: '3'
services:
  application:
    build: .
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - main_network

  loadbalancer:
    build: ./loadbalancer
    ports:
      - 80:80
    networks:
      - main_network
    depends_on:
      - application

networks:
  main_network:
